### ISSUE TITLE
小米手机上报这个问题com.litesuits.http.exception.NetException: Service Unreachable, or Network Is Unstable (服务无法访问)

### ISSUE THREAD

**Issue by YWD** [litesuits/android-lite-http#24]
把图片转成base64字符串了，两张图片可以传，多了就不行了，为什么，魅族手机没问题？
 at com.litesuits.http.impl.apache.ApacheHttpClient.connectWithRetries(ApacheHttpClient.java:405)
    at com.litesuits.http.LiteHttp.tryToConnectNetwork(LiteHttp.java:434)
    at com.litesuits.http.LiteHttp.execute(LiteHttp.java:217)
    at com.litesuits.http.LiteHttp$1.run(LiteHttp.java:268)
    at com.litesuits.http.concurrent.SmartExecutor$2.run(SmartExecutor.java:179)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
Caused by: javax.net.ssl.SSLException: Write error: ssl=0x9fdee800: I/O error during system call, Connection reset by peer
     at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
     at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:771)
     at org.apache.http.impl.io.AbstractSessionOutputBuffer.write(AbstractSessionOutputBuffer.java:114)
     at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:118)
     at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:124)
     at org.apache.http.entity.StringEntity.writeTo(StringEntity.java:94)
     at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:102)
     at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:167)
     at org.apache.http.impl.conn.AbstractClientConnAdapter.sendRequestEntity(AbstractClientConnAdapter.java:277)
     at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:242)
     at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
     at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:444)
     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
     at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
     at com.litesuits.http.impl.apache.ApacheHttpClient.connectWithRetries(ApacheHttpClient.java:277)

**Comment by YWD** [comment]
把图片转成base64字符串了，两张图片可以传，多了就不行了，为什么，魅族手机没问题？
at com.litesuits.http.impl.apache.ApacheHttpClient.connectWithRetries(ApacheHttpClient.java:405)
at com.litesuits.http.LiteHttp.tryToConnectNetwork(LiteHttp.java:434)
at com.litesuits.http.LiteHttp.execute(LiteHttp.java:217)
at com.litesuits.http.LiteHttp$1.run(LiteHttp.java:268)
at com.litesuits.http.concurrent.SmartExecutor$2.run(SmartExecutor.java:179)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
at java.lang.Thread.run(Thread.java:818)
Caused by: javax.net.ssl.SSLException: Write error: ssl=0x9fdee800: I/O error during system call, Connection reset by peer
at com.android.org.conscrypt.NativeCrypto.SSL_write(Native Method)
at com.android.org.conscrypt.OpenSSLSocketImpl$SSLOutputStream.write(OpenSSLSocketImpl.java:771)
at org.apache.http.impl.io.AbstractSessionOutputBuffer.write(AbstractSessionOutputBuffer.java:114)
at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:118)
at org.apache.http.impl.io.ContentLengthOutputStream.write(ContentLengthOutputStream.java:124)
at org.apache.http.entity.StringEntity.writeTo(StringEntity.java:94)
at org.apache.http.impl.entity.EntitySerializer.serialize(EntitySerializer.java:102)
at org.apache.http.impl.AbstractHttpClientConnection.sendRequestEntity(AbstractHttpClientConnection.java:167)
at org.apache.http.impl.conn.AbstractClientConnAdapter.sendRequestEntity(AbstractClientConnAdapter.java:277)
at org.apache.http.protocol.HttpRequestExecutor.doSendRequest(HttpRequestExecutor.java:242)
at org.apache.http.protocol.HttpRequestExecutor.execute(HttpRequestExecutor.java:124)
at org.apache.http.impl.client.DefaultRequestDirector.execute(DefaultRequestDirector.java:444)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:560)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:492)
at org.apache.http.impl.client.AbstractHttpClient.execute(AbstractHttpClient.java:470)
at com.litesuits.http.impl.apache.ApacheHttpClient.connectWithRetries(ApacheHttpClient.java:277)
