### ISSUE TITLE
你们用这个框架的时候有没有报ConcurrentModificationException？

### ISSUE THREAD

**Issue by feiyu65535** [litesuits/android-lite-http#31]
java.util.ConcurrentModificationException
	at java.util.LinkedHashMap$LinkedHashIterator.nextEntry(LinkedHashMap.java:346)
	at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:375)
	at java.util.LinkedHashMap$EntryIterator.next(LinkedHashMap.java:375)
	at com.litesuits.http.request.AbstractRequest.reqToString(AbstractRequest.java)
	at com.litesuits.http.request.AbstractRequest.toString(AbstractRequest.java)
	at java.lang.StringBuilder.append(StringBuilder.java:202)

感觉是reqToString中没有做线程安全处理导致，现在这个bug友盟每天都报，是我这个项目里最大的bug。

**Comment by feiyu65535** [comment]
已经联系作者解决
